name:                haskell

dependencies:
- base >= 4.7 && < 5
- split
- megaparsec
- hashable
- matrix
- containers
- unordered-containers
- vector
- array
- criterion
- hspec

library:
  source-dirs: src

_exe-ghc-options: &exe-ghc-options
 - -O2
 - -threaded
 - -funfolding-use-threshold=16
 - -fexcess-precision
 - -optc-O3
 - -optc-ffast-math
 - -Wall
 - -Wno-type-defaults
 - -Wno-unused-do-bind

_exe_options:     &exe-options
  source-dirs:    [app]
  ghc-options:    *exe-ghc-options

executables:
  all:
    main:         Main.main
    <<:         *exe-options
    dependencies:
    - haskell
  # d01:
  #   main:       D01.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  # d04:
  #   main:       D04.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - split
  # d06:
  #   main:       D06.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - matrix
  #   - split
  # d07:
  #   main:       D07.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - split
  # d08:
  #   main:       D08.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - split
  #   - containers
  # d09:
  #   main:       D09.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - unordered-containers
  # d10:
  #   main:       D10.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  # d12:
  #   main:       D12.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - split
  #   - unordered-containers
  #   - hashable
  # d13:
  #   main:       D13.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - megaparsec
  #   - unordered-containers
  # d14:
  #   main:       D14.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - megaparsec
  #   - unordered-containers
  # d16:
  #   main:       D16.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - megaparsec
  #   - unordered-containers
  # d17:
  #   main:       D17.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - megaparsec
  # d21:
  #   main:       D21.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  # d22:
  #   main:       D22.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  # d25:
  #   main:       D25.main
  #   <<:         *exe-options
  #   dependencies:
  #   - haskell
  #   - array

benchmarks:
  d22-bench:
    main: D22Bench.main
    source-dirs: bench
    dependencies:
    - base
    - haskell
    - criterion
    ghc-options:    *exe-ghc-options

tests:
  d22-test:
    main:           Spec.hs
    source-dirs:    [app, test]
    ghc-options:    *exe-ghc-options
    dependencies:
    - haskell
