name:                haskell

dependencies:
- base >= 4.7 && < 5
- split
- megaparsec
- hashable
- matrix
- containers
- unordered-containers
- vector
- array
- criterion
- hspec

library:
  source-dirs: src

_exe-ghc-options: &exe-ghc-options
 - -O2
 - -threaded
 - -funfolding-use-threshold=16
 - -fexcess-precision
 - -optc-O3
 - -optc-ffast-math
 - -Wall
 - -Wno-type-defaults
 - -Wno-unused-do-bind

_exe_options:     &exe-options
  source-dirs:    [app]
  ghc-options:    *exe-ghc-options

executables:
  all:
    main:         Main.main
    <<:         *exe-options
    dependencies:
    - haskell

benchmarks:
  d22-bench:
    main: D22Bench.main
    source-dirs: bench
    dependencies:
    - base
    - haskell
    - criterion
    ghc-options:    *exe-ghc-options

tests:
  d22-test:
    main:           Spec.hs
    source-dirs:    [app, test]
    ghc-options:    *exe-ghc-options
    dependencies:
    - haskell
