name:                d25
version:             0.1.0.0
github:              "TrebledJ/aoc"
license:             BSD3
author:              "TrebledJ"
maintainer:          ""
copyright:           "2021 TrebledJ"

extra-source-files: []

description:         Day 25 of my AOC 2020 solutions.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  d25:
    main:                Main.hs
    source-dirs:         [app, src]
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - d25
